execute_process(COMMAND "${HOST}" --help RESULT_VARIABLE result OUTPUT_VARIABLE output)
if(NOT result EQUAL 0 OR NOT output MATCHES "capture-seconds")
  message(FATAL_ERROR "Host help missing capture mode")
endif()
foreach(value 0 -1 121 junk 1junk)
  execute_process(COMMAND "${HOST}" --capture-seconds "${value}" RESULT_VARIABLE result)
  if(NOT result EQUAL 2)
    message(FATAL_ERROR "Invalid capture duration did not fail before consent: ${value}")
  endif()
endforeach()
foreach(value 0 -1 4 junk 2junk)
  execute_process(COMMAND "${HOST}" --capture-seconds 1 --capture-runs "${value}" RESULT_VARIABLE result)
  if(NOT result EQUAL 2)
    message(FATAL_ERROR "Invalid run count accepted: ${value}")
  endif()
endforeach()
execute_process(COMMAND "${HOST}" --capture-runs 2 RESULT_VARIABLE result)
if(NOT result EQUAL 2)
  message(FATAL_ERROR "Run count without capture mode accepted")
endif()
execute_process(COMMAND "${HOST}" --bitrate-mbps 12 --capture-runs 2 RESULT_VARIABLE result)
if(NOT result EQUAL 2)
  message(FATAL_ERROR "Run count attached to bitrate accepted")
endif()
execute_process(COMMAND "${HOST}" --capture-seconds RESULT_VARIABLE result)
if(NOT result EQUAL 2)
  message(FATAL_ERROR "Missing capture duration accepted")
endif()
if(LINUX_CAPTURE)
  execute_process(COMMAND "${CMAKE_COMMAND}" -E env --unset=DBUS_SESSION_BUS_ADDRESS --unset=XDG_SESSION_TYPE "${HOST}" --capture-seconds 1 RESULT_VARIABLE result OUTPUT_VARIABLE output)
  if(NOT result EQUAL 1 OR NOT output MATCHES "host.capture_failed" OR NOT output MATCHES "CAPTURE_FAILED" OR NOT output MATCHES "OFFLINE")
    message(FATAL_ERROR "Missing-session capture failure did not complete host cleanup")
  endif()
else()
  execute_process(COMMAND "${HOST}" --capture-seconds 1 RESULT_VARIABLE result)
  if(NOT result EQUAL 2)
    message(FATAL_ERROR "Unavailable capture backend was not reported")
  endif()
endif()
