foreach(value 0 301 -1 1x)
  execute_process(COMMAND "${MOTION}" --seconds "${value}" RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET TIMEOUT 3)
  if(NOT status EQUAL 2)
    message(FATAL_ERROR "Invalid duration ${value} returned ${status}")
  endif()
endforeach()
foreach(argument --seconds --unknown)
  execute_process(COMMAND "${MOTION}" "${argument}" RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET TIMEOUT 3)
  if(NOT status EQUAL 2)
    message(FATAL_ERROR "Invalid argument ${argument} returned ${status}")
  endif()
endforeach()
execute_process(COMMAND "${MOTION}" --help RESULT_VARIABLE status OUTPUT_VARIABLE output TIMEOUT 3)
if(NOT status EQUAL 0 OR NOT output MATCHES "--seconds")
  message(FATAL_ERROR "Missing motion source help")
endif()
foreach(arguments "--composition-control;--seconds;1" "--seconds;1;--composition-control")
  execute_process(COMMAND "${CMAKE_COMMAND}" -E env WAYLAND_DISPLAY=/nonexistent/cloudplay-test
    "${MOTION}" ${arguments} RESULT_VARIABLE status ERROR_VARIABLE error TIMEOUT 3)
  if(NOT status EQUAL 1 OR NOT error MATCHES "Wayland connection unavailable")
    message(FATAL_ERROR "Composition control CLI rejected valid options: ${status} ${error}")
  endif()
endforeach()
foreach(arguments "--composition-control;--composition-control" "--seconds;1;--seconds;2" "--composition-control;--seconds")
  execute_process(COMMAND "${MOTION}" ${arguments} RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET TIMEOUT 3)
  if(NOT status EQUAL 2)
    message(FATAL_ERROR "Invalid repeated/missing option accepted: ${arguments}")
  endif()
endforeach()
execute_process(COMMAND "${CMAKE_COMMAND}" -E env WAYLAND_DISPLAY=/nonexistent/cloudplay-test
  "${MOTION}" --seconds 1 RESULT_VARIABLE status OUTPUT_QUIET ERROR_VARIABLE error TIMEOUT 3)
if(NOT status EQUAL 1 OR NOT error MATCHES "Wayland connection unavailable")
  message(FATAL_ERROR "Missing display did not fail cleanly: ${status} ${error}")
endif()
