if(NOT DEFINED PROBE)
  message(FATAL_ERROR "Capture probe executable required")
endif()

function(run_probe expected)
  execute_process(
    COMMAND "${CMAKE_COMMAND}" -E env --unset=DBUS_SESSION_BUS_ADDRESS --unset=XDG_SESSION_TYPE "${PROBE}" ${ARGN}
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 5)
  if(NOT result EQUAL expected)
    message(FATAL_ERROR "Unexpected probe exit ${result}: ${ARGN}\n${output}\n${error}")
  endif()
  set(probe_output "${output}" PARENT_SCOPE)
endfunction()

run_probe(2 --source)
run_probe(2 --source virtual)
run_probe(2 --source monitor --source window)
run_probe(2 --fixed-rate --fixed-rate)
run_probe(2 --timing-diagnostics --timing-diagnostics)
run_probe(2 --source monitor --seconds 0)
run_probe(2 --cpu-capture --cpu-capture)
run_probe(2 --cpu-capture --snapshot /tmp/not-created.png)
run_probe(2 --buffer-pool 1)
run_probe(2 --buffer-pool 9)
run_probe(2 --buffer-pool 4 --buffer-pool 8)
run_probe(2 --diagnostic-max-fps 59)
run_probe(2 --diagnostic-max-fps 66)
run_probe(2 --diagnostic-max-fps 61x)
run_probe(2 --diagnostic-max-fps 61 --diagnostic-max-fps 62)
run_probe(2 --diagnostic-max-fps 61 --fixed-rate)
run_probe(1 --diagnostic-max-fps 61 --seconds 30)
string(REPLACE "\n" ";" maximum_lines "${probe_output}")
list(GET maximum_lines 0 maximum_request)
string(JSON maximum GET "${maximum_request}" maximumFps)
if(NOT maximum EQUAL 61)
  message(FATAL_ERROR "Diagnostic ceiling not reported")
endif()

run_probe(1 --cpu-capture --buffer-pool 8 --source monitor --seconds 30 --timing-diagnostics)
string(REPLACE "\n" ";" control_lines "${probe_output}")
list(GET control_lines 0 control)
string(JSON cpu GET "${control}" cpuCapture)
string(JSON pool GET "${control}" requestedBufferPoolSize)
string(JSON fixed GET "${control}" fixedRate)
if(NOT cpu OR NOT pool EQUAL 8 OR fixed)
  message(FATAL_ERROR "CPU control did not preserve range negotiation or pool selection")
endif()

run_probe(1 --seconds 1)
string(REPLACE "\n" ";" baseline_lines "${probe_output}")
list(GET baseline_lines 0 baseline)
string(JSON fixed GET "${baseline}" fixedRate)
string(JSON timing GET "${baseline}" timingDiagnostics)
string(JSON types GET "${baseline}" requestedSourceTypes)
if(fixed OR timing OR NOT types EQUAL 3)
  message(FATAL_ERROR "Default capture experiment options changed")
endif()

foreach(source IN ITEMS any monitor window)
  run_probe(1 --source "${source}" --timing-diagnostics --fixed-rate --seconds 30)
  string(REPLACE "\n" ";" lines "${probe_output}")
  list(GET lines 0 request)
  string(JSON event GET "${request}" event)
  string(JSON fixed GET "${request}" fixedRate)
  string(JSON timing GET "${request}" timingDiagnostics)
  string(JSON types GET "${request}" requestedSourceTypes)
  if(source STREQUAL "any")
    set(expected_types 3)
  elseif(source STREQUAL "monitor")
    set(expected_types 1)
  else()
    set(expected_types 2)
  endif()
  if(NOT event STREQUAL "capture.requested_rate" OR NOT fixed OR NOT timing OR NOT types EQUAL expected_types)
    message(FATAL_ERROR "CLI did not forward capture experiment options: ${request}")
  endif()
  list(GET lines 1 durations)
  string(JSON samples GET "${durations}" stages arrivalInterval count)
  if(NOT samples EQUAL 0)
    message(FATAL_ERROR "Missing session reported capture timing samples")
  endif()
endforeach()
